name: Update HackerRank Stats

on:
  schedule:
    # Runs every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch: # This line allows you to run it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update HackerRank Stats
        uses: rishabh-in/HackerRank-stats-readme@v1
        with:
          # Make sure this is your exact HackerRank username
          HACKERRANK_USERNAME: anandkumarchatr1
